version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mybank_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mybank_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mybank_backend
    restart: unless-stopped
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@database:3306/${DB_NAME}?serverVersion=8.0&charset=utf8mb4
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - database
    networks:
      - mybank_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mybank_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mybank_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mybank_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - mybank_network

volumes:
  mysql_data:

networks:
  mybank_network:
    driver: bridge